apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spring-forward.fullname" . }}
  labels:
    {{- include "spring-forward.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "spring-forward.selectorLabels" . | nindent 4 }}
  endpoints:
  - port: 8080
    path: "/actuator/prometheus"
